//try catch
const num1 = 20;
const num2 = 30;

try {
    console.log(num1);
} catch (error) {
    console.log(error);
}